'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import type { LuminateDataset } from '@/lib/types';
import { computeOverviewKPIs, computeGrowthMetrics, computeDealInsights, computeArtistTimeline, computeSongAggregations, defaultFilters } from '@/lib/analytics';
import { formatNumber, formatCurrency, formatPct, formatTrend, trendColor } from '@/lib/utils';
import { AreaChart, Area, XAxis, YAxis, Tooltip, ResponsiveContainer } from 'recharts';

export default function SharePage() {
  const params = useParams();
  const [data, setData] = useState<LuminateDataset | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function load() {
      try {
        const res = await fetch(`/api/artists/${params.id}`);
        if (!res.ok) throw new Error('Report not found');
        setData(await res.json());
      } catch (err) { setError(err instanceof Error ? err.message : 'Failed'); }
    }
    if (params.id) load();
  }, [params.id]);

  if (error) return <div className="home-page" style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: '100vh' }}><p>{error}</p></div>;
  if (!data) return <div className="home-page" style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', minHeight: '100vh' }}><div className="home-loading"><div className="spinner" /></div></div>;

  const kpis = computeOverviewKPIs(data);
  const growth = computeGrowthMetrics(data);
  const deal = computeDealInsights(data, defaultFilters);
  const timeline = computeArtistTimeline(data);
  const songs = computeSongAggregations(data, defaultFilters);

  return (
    <div style={{ maxWidth: 900, margin: '0 auto', padding: '2rem' }}>
      <div style={{ textAlign: 'center', marginBottom: '2rem', borderBottom: '1px solid var(--border-subtle)', paddingBottom: '1.5rem' }}>
        <h1 style={{ fontSize: '2rem', fontWeight: 800, marginBottom: '0.25rem' }}>{kpis.artistName}</h1>
        <p style={{ color: 'var(--text-secondary)' }}>{kpis.genre} • {kpis.timeFrame} • Streaming Analytics Report</p>
        <p style={{ color: 'var(--text-tertiary)', fontSize: '0.75rem', marginTop: '0.5rem' }}>Generated by Luminate Analyzer</p>
      </div>

      <div className="kpi-grid" style={{ marginBottom: '2rem' }}>
        <div className="stat-card highlight"><div className="stat-card-label">All-Time Streams</div><div className="stat-card-value">{formatNumber(kpis.totalATD)}</div></div>
        <div className="stat-card"><div className="stat-card-label">YTD Streams</div><div className="stat-card-value">{formatNumber(kpis.ytdStreams)}</div><div className="stat-card-trend" style={{ color: trendColor(growth.trailing12WvsP12) }}>{formatTrend(growth.trailing12WvsP12)}</div></div>
        <div className="stat-card"><div className="stat-card-label">This Week</div><div className="stat-card-value">{formatNumber(kpis.currentWeekStreams)}</div></div>
        <div className="stat-card"><div className="stat-card-label">12W Average</div><div className="stat-card-value">{formatNumber(kpis.trailingAvg12W)}</div></div>
        <div className="stat-card"><div className="stat-card-label">Top Song</div><div className="stat-card-value" style={{ fontSize: '1.1rem' }}>{kpis.topSongTitle}</div></div>
        <div className="stat-card"><div className="stat-card-label">Est. Annual Revenue</div><div className="stat-card-value">{formatCurrency(deal.revenueEstimateLow)}–{formatCurrency(deal.revenueEstimateHigh)}</div></div>
      </div>

      <div className="chart-card" style={{ marginBottom: '2rem' }}>
        <h3 style={{ marginBottom: '1rem' }}>Streaming Timeline</h3>
        <ResponsiveContainer width="100%" height={250}>
          <AreaChart data={timeline}>
            <defs><linearGradient id="sg" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#6366f1" stopOpacity={0.25}/><stop offset="100%" stopColor="#6366f1" stopOpacity={0}/></linearGradient></defs>
            <XAxis dataKey="date" tick={{ fill: '#5a5c72', fontSize: 11 }} tickLine={false} axisLine={false} interval={Math.floor(timeline.length / 6)} />
            <YAxis tick={{ fill: '#5a5c72', fontSize: 11 }} tickLine={false} axisLine={false} tickFormatter={(v: any) => formatNumber(v)} width={45} />
            <Tooltip contentStyle={{ background: '#111113', border: '1px solid #1c1c1f', borderRadius: 8 }} />
            <Area type="monotone" dataKey="quantity" stroke="#6366f1" strokeWidth={2} fill="url(#sg)" />
          </AreaChart>
        </ResponsiveContainer>
      </div>

      <div className="chart-card">
        <h3 style={{ marginBottom: '1rem' }}>Top Songs</h3>
        <div className="data-table-wrap">
          <table className="data-table">
            <thead><tr><th>#</th><th>Song</th><th className="text-right">ATD</th><th className="text-right">This Week</th><th>Trend</th></tr></thead>
            <tbody>
              {songs.slice(0, 15).map((s, i) => (
                <tr key={s.luminateId}>
                  <td className="mono" style={{ color: 'var(--text-tertiary)' }}>{i + 1}</td>
                  <td className="song-title">{s.title}</td>
                  <td className="mono text-right">{formatNumber(s.atd)}</td>
                  <td className="mono text-right">{formatNumber(s.currentWeek)}</td>
                  <td><span className={`trend-badge ${s.trend}`}>{s.trend === 'up' ? '↑' : s.trend === 'down' ? '↓' : '→'} {Math.abs(s.trendPct)}%</span></td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
